baseURL = "/"
title = "Manuel Aguilar"
paginate = 5
theme = [ "hugo-PaperMod" ]
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = [ "posts", "papermod" ]

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "blockchain"
url = "blockchain/"
weight = 10

[[languages.en.menu.main]]
name = "bioinformatics"
url = "bioinformatics/"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "portfolio website"
author = "Manuel Aguilar"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
images = [ "images/papermod-cover.png" ]

[params.profileMode]
enabled = false
title = "PaperMod"
imageUrl = "#"
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Archives"
url = "archives"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "Research blog."
Content = """
Showcasing my interests in computing.
"""

[[params.socialIcons]]
name = "github"
title = "Github Profile"
url = "https://github.com/manguilar22"

[[params.socialIcons]]
name = "linkedin"
title = "Linkedin Profile"
url = "https://www.linkedin.com/in/manuel-aguilar-860118190"

[params.assets]
disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = false

[services.twitter]
disableInlineCSS = false
